name: First Ascent Photography
favicon: null
layout_spectrum: 0.8365029769483954
typography_spectrum: 0.4979267353191972
title: First Ascent Photography
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#183853'
    - '#d8ae79'
    - '#2b638d'
    - '#000000'
    - '#8c6948'
  brandStrength: 0.5
  lightness: 0.4983990848995745
  saturation: 0.25
  rhythmicContrast: 0.11556897778064013
purpose: []
