name: First Ascent Photography
favicon: null
layout_spectrum: 0.8365029769483954
typography_spectrum: 0.4979267353191972
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.8131953210104257
  lightness: 0.4983990848995745
  saturation: 0.45023499545641243
  rhythmicContrast: 0.11556897778064013
purpose: []
